swagger: "2.0"
info:
  description: Api config for app.
  version: "1.0.0"
  title: Rest Api Config
consumes:
  - application/json
produces:
  - application/json

basePath: /api

paths:
  /traindata:
    get:
      operationId: operations.train_read_all
      tags:
        - TrainData
      summary: Read the entire list of traindata
      description: Read the list of traindata
      parameters:
        - name: length
          in: query
          type: integer
          description: Number of traindata to get from traindata
          required: false
        - name: offset
          in: query
          type: integer
          description: Offset from beginning of list where to start gathering traindata
          required: false
      responses:
        200:
          description: Successfully read traindata list operation
          schema:
            type: object
            items:
              properties:
                req_id:
                  type: string
                mongo_id:
                  type: object

    post:
      operationId: operations.train_create
      tags:
        - TrainData
      summary: Create a new instance of traindata and add it to the traindata list
      description: Create a new instance of traindata in the traindata list
      parameters:
        - name: t_data_instance
          in: body
          description: Traindata to create
          required: True
          schema:
            type: object
            properties:
              DATA:
                type: object
                description: Array of train data to create
      responses:
        201:
          description: Successfully created instance of traindata in list

  /traindata/{req_id}:
    put:
      operationId: operations.train_completed
      tags:
      - TrainData
      summary: Update a traindata instance in the traindata list
      description: Update a traindata instance in the traindata list
      parameters:
      - name: req_id
        in: path
        description: ID of request
        type: string
        required: True
      responses:
        200:
          description: Successfully updated person in people list


  /testdata:
    get:
      operationId: operations.test_read_all
      tags:
        - TestData
      summary: Read the entire list of testdata
      description: Read the list of testdata
      parameters:
        - name: length
          in: query
          type: integer
          description: Number of testdata to get from testdata
          required: false
        - name: offset
          in: query
          type: integer
          description: Offset from beginning of list where to start gathering testdata
          required: false
      responses:
        200:
          description: Successfully read testdata list operation
          schema:
            type: object
            items:
              properties:
                req_id:
                  type: string
                mongo_id:
                  type: object

    post:
      operationId: operations.test_create
      tags:
        - TestData
      summary: Create a new instance of testdata and add it to the testdata list
      description: Create a new instance of testdata in the testdata list
      parameters:
        - name: t_data_instance
          in: body
          description: Traindata to create
          required: True
          schema:
            type: object
            properties:
              DATA:
                type: object
                description: Array of train data to create
      responses:
        201:
          description: Successfully created instance of testdata in list

  /testdata/{req_id}:
    put:
      operationId: operations.test_start
      tags:
      - TestData
      summary: Update a testdata instance in the testdata list
      description: Update a testdata instance in the testdata list
      parameters:
      - name: req_id
        in: path
        description: ID of request
        type: string
        required: True
      responses:
        200:
          description: Successfully updated person in people list

    post:
      operationId: operations.test_completed
      tags:
      - TestData
      summary: Receive test result
      description: Receive test result
      parameters:
      - name: req_id
        in: path
        description: ID of request
        type: string
        required: True
      - name: t_data_res
        in: body
        description: Traindata to create
        required: True
        schema:
          type: object
          properties:
            DATA:
              type: object
              description: Array of test data results
      responses:
        201:
          description: Successfully received test data results

  /testres:
    get:
      operationId: operations.test_read_all_res
      tags:
      - TestData
      summary: Read the entire list of testdata
      description: Read the list of testdata
      parameters:
      - name: length
        in: query
        type: integer
        description: Number of testdata to get from testdata
        required: false
      - name: offset
        in: query
        type: integer
        description: Offset from beginning of list where to start gathering testdata
        required: false
      responses:
        200:
          description: Successfully read testdata list operation
          schema:
            type: object
            items:
              properties:
                req_id:
                  type: string
                mongo_id:
                  type: object

  /testres/{req_id}:
    get:
      operationId: operations.test_read_one_res
      tags:
      - TestData
      summary: Read one test data result, by request id
      description: Read one test data result, by request id
      parameters:
      - name: req_id
        in: path
        description: ID of request
        type: string
        required: True
      responses:
        200:
          description: Successfully read one test data result
          schema:
            properties:
              req_id:
                type: array