swagger: "2.0"
info:
  description: Api config for app.
  version: "1.0.0"
  title: Rest Api Config
consumes:
  - application/json
produces:
  - application/json

basePath: /api


paths:
  /traindata:
    get:
      operationId: traindata.read_all
      tags:
        - TrainData
      summary: Read the entire list of traindata
      description: Read the list of traindata
      parameters:
        - name: length
          in: query
          type: integer
          description: Number of traindata to get from traindata
          required: false
        - name: offset
          in: query
          type: integer
          description: Offset from beginning of list where to start gathering traindata
          required: false
      responses:
        200:
          description: Successfully read traindata list operation
          schema:
            type: array
            items:
              properties:
                dataid:
                  type: string
                DATA:
                  type: object
                timestamp:
                  type: string

    post:
      operationId: traindata.create
      tags:
        - TrainData
      summary: Create a new instance of traindata and add it to the traindata list
      description: Create a new instance of traindata in the traindata list
      parameters:
        - name: t_data_instance
          in: body
          description: Traindata to create
          required: True
          schema:
            type: object
            properties:
              DATA:
                type: object
                description: Array of train data to create
      responses:
        201:
          description: Successfully created instance of traindata in list

  /traindata/{dataid}:
    get:
      operationId: traindata.read_one
      tags:
        - TrainData
      summary: Read one traindata instance from the traindata list
      description: Read one traindata instance from the traindata list
      parameters:
        - name: dataid
          in: path
          description: dataid of the traindata instance to get from the list
          type: string
          required: True
      responses:
        200:
          description: Successfully read traindata instance from traindata list operation
          schema:
            properties:
              dataid:
                type: integer
              DATA:
                type: object
              timestamp:
                type: string

    delete:
      operationId: traindata.delete
      tags:
        - TrainData
      summary: Delete a traindata instance from the traindata list
      description: Delete a traindata instance
      parameters:
        - name: dataid
          in: path
          type: string
          required: True
      responses:
        200:
          description: Successfully deleted a traindata instance from traindata list

  /testdata:
    get:
      operationId: testdata.read_all
      tags:
      - TestData
      summary: Read the entire list of testdata
      description: Read the list of testdata
      parameters:
      - name: length
        in: query
        type: integer
        description: Number of testdata to get from testdata
        required: false
      - name: offset
        in: query
        type: integer
        description: Offset from beginning of list where to start gathering testdata
        required: false
      responses:
        200:
          description: Successfully read testdata list operation
          schema:
            type: array
            items:
              properties:
                dataid:
                  type: string
                DATA:
                  type: object
                timestamp:
                  type: string

#  /testdata/{dataid}:
#    get:
#      operationId: testdata.read_one
#      tags:
#      - TestData
#      summary: Read one testdata instance from the testdata list
#      description: Read one testdata instance from the testdata list
#      parameters:
#      - name: dataid
#          in: path
#          description: dataid of the testdata instance to get from the list
#          type: string
#          required: True
#      responses:
#        200:
#          description: Successfully read testdata instance from testdata list operation
#          schema:
#            properties:
#              dataid:
#                type: string
#              DATA:
#                type: object
#              timestamp:
#                type: string

#    delete:
#      operationId: testdata.delete
#      tags:
#      - TestData
#      summary: Delete a testdata instance from the testdata list
#      description: Delete a testdata instance
#      parameters:
#      - name: dataid
#        in: path
#        type: string
#        required: True
#      responses:
#        200:
#          description: Successfully deleted a testdata instance from testdata list

  /testdata/getlast:
    get:
      operationId: testdata.read_latest
      tags:
      - TestData
      summary: Read latest testdata instance from the testdata list
      description: Read latest testdata instance from the testdata list
      responses:
        200:
          description: Successfully read latest testdata instance from testdata list operation
          schema:
            properties:
              dataid:
                type: string
              DATA:
                type: object
              timestamp:
                type: string