swagger: "2.0"
info:
  description: Api config for app.
  version: "1.0.0"
  title: Rest Api Config
consumes:
  - application/json
produces:
  - application/json

basePath: /api

paths:
  /traindata:
    get:
      operationId: operations.train_read_all
      tags:
        - TrainData
      summary: Read the entire list of traindata
      description: Read the list of traindata
      parameters:
        - name: length
          in: query
          type: integer
          description: Number of traindata to get from traindata
          required: false
        - name: offset
          in: query
          type: integer
          description: Offset from beginning of list where to start gathering traindata
          required: false
      responses:
        200:
          description: Successfully read traindata list operation
          schema:
            type: object
            items:
              properties:
                req_id:
                  type: string
                mongo_id:
                  type: object


  /traindata/{project}/{model}:
    post:
      operationId: operations.train_create
      tags:
        - TrainData
      summary: Create a new instance of traindata and add it to the traindata list
      description: Create a new instance of traindata in the traindata list
      parameters:
        - name: project
          in: path
          description: Project name
          type: string
          required: True
        - name: model
          in: path
          description: Model name
          type: string
          required: True
        - name: t_data_instance
          in: body
          description: Traindata to create
          required: True
          schema:
            type: object
            properties:
              DATA:
                type: object
                description: Array of train data to create
      responses:
        200:
          description: Training started
          schema:
            properties:
              status:
                type: string


  /traindata/isfinished/{req_id}:
    get:
      operationId: operations.train_is_finished
      tags:
      - TrainData
      summary: Read the entire list of traindata
      description: Read the list of traindata
      parameters:
      - name: req_id
        in: path
        description: REQUEST ID
        type: string
        required: True
      responses:
        200:
          description: Successfully read traindata list operation
          schema:
            properties:
              status:
                type: string

  /testdata:
    post:
      operationId: operations.test_create
      tags:
      - TestData
      summary: Create a new instance of testdata and add it to the testdata list
      description: Create a new instance of testdata in the testdata list
      parameters:
      - name: t_data_instance
        in: body
        description: Traindata to create
        required: True
        schema:
          type: object
          properties:
            DATA:
              type: object
              description: Array of train data to create
      responses:
        200:
          description: Successfully read one test data result
          schema:
            properties:
              req_id:
                type: array

  /testres:
    get:
      operationId: operations.test_read_all_res
      tags:
      - TestData
      summary: Read the entire list of testdata
      description: Read the list of testdata
      parameters:
      - name: length
        in: query
        type: integer
        description: Number of testdata to get from testdata
        required: false
      - name: offset
        in: query
        type: integer
        description: Offset from beginning of list where to start gathering testdata
        required: false
      responses:
        200:
          description: Successfully read testdata list operation
          schema:
            type: object
            items:
              properties:
                req_id:
                  type: string
                mongo_id:
                  type: object

  /projects:
    get:
      operationId: operations.get_all_projects
      tags:
      - ProjList
      summary: Get available projects list
      description: Get available projects list
      parameters:
      - name: length
        in: query
        type: integer
        description: Number of projects to get from proj_list
        required: false
      responses:
        200:
          description: Successfully read testdata list operation
          schema:
            properties:
              proj_list:
                type: array

  /models/{project}:
    get:
      operationId: operations.get_all_models
      tags:
      - ModelsList
      summary: Get available models list
      description: Get available models list
      parameters:
      - name: project
        in: path
        description: Project name
        type: string
        required: True
      - name: length
        in: query
        type: integer
        description: Number of models to get from proj_list
        required: false
      responses:
        200:
          description: Successfully read models list operation
          schema:
            properties:
              models_list:
                type: array

  /interpreter/{project}/{model}/{force}:
    post:
      operationId: operations.update_interpreter
      tags:
      - Interpreter
      summary: Load interpreter
      description: Load interpreter
      parameters:
      - name: project
        in: path
        description: Project name
        type: string
        required: True
      - name: model
        in: path
        description: Model name
        type: string
        required: True
      - name: force
        in: path
        description: Force interpreter update
        type: string
        required: True
      - name: model_path
        in: body
        description: sdfasdf
        required: True
        schema:
          type: object
          properties:
            DATA:
              type: string
              description: Array of ids
      responses:
        201:
          description: Successfully loaded interpreter

  /interpreter/isloaded/{project}/{model}:
    get:
      operationId: operations.interpreter_is_loaded
      tags:
      - Interpreter
      summary: Check if interpreter is loaded
      description: Check if interpreter is loaded
      parameters:
      - name: project
        in: path
        description: Project name
        type: string
        required: True
      - name: model
        in: path
        description: Model name
        type: string
        required: True
      responses:
        200:
          description: Checked
          schema:
            properties:
              status:
                type: string