swagger: "2.0"
info:
  description: Api config for app.
  version: "1.0.0"
  title: Rest Api Config
consumes:
  - application/json
produces:
  - application/json

basePath: /api

paths:
  /traindata:
    get:
      operationId: traindata.read_all
      tags:
        - TrainData
      summary: Read the entire list of traindata
      description: Read the list of traindata
      parameters:
        - name: length
          in: query
          type: integer
          description: Number of traindata to get from traindata
          required: false
        - name: offset
          in: query
          type: integer
          description: Offset from beginning of list where to start gathering traindata
          required: false
      responses:
        200:
          description: Successfully read traindata list operation
          schema:
            type: object
            items:
              properties:
                req_id:
                  type: string
                mongo_id:
                  type: object

    post:
      operationId: traindata.create
      tags:
        - TrainData
      summary: Create a new instance of traindata and add it to the traindata list
      description: Create a new instance of traindata in the traindata list
      parameters:
        - name: t_data_instance
          in: body
          description: Traindata to create
          required: True
          schema:
            type: object
            properties:
              DATA:
                type: object
                description: Array of train data to create
      responses:
        201:
          description: Successfully created instance of traindata in list

  /traindata/{req_id}:
    put:
      operationId: traindata.completed
      tags:
      - TrainData
      summary: Update a traindata instance in the traindata list
      description: Update a traindata instance in the traindata list
      parameters:
      - name: req_id
        in: path
        description: ID of request
        type: string
        required: True
      responses:
        200:
          description: Successfully updated person in people list
